spring:
  datasource:
    member:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 180000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        jdbcUrl: jdbc:mysql://106.55.40.222:3306/pile_member?useUnicode=true&serverTimezone=UTC&useSSL=false
        username: root
        password: 123qqq...A
    config:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 180000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        jdbcUrl: jdbc:mysql://106.55.40.222:3306/pile_config?useUnicode=true&serverTimezone=UTC&useSSL=false
        username: root
        password: 123qqq...A
    bill:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 180000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        jdbcUrl: jdbc:mysql://106.55.40.222:3306/pile_bill?useUnicode=true&serverTimezone=UTC&useSSL=false
        username: root
        password: 123qqq...A
    screen:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 180000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        jdbcUrl: jdbc:mysql://106.55.40.222:3306/big_screen_test?useUnicode=true&serverTimezone=UTC&useSSL=false
        username: root
        password: 123qqq...A

  redis:
    database: 0
    host: 106.55.40.222
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: richcomm2016
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

server:
  port: 8091

sellerId: 20
userId: 1
expireTime: 60
